apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: voting-app-database
  labels:
    app: voting-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd-storagepool-cluster
  resources:
    requests:
      storage: 1Gi
