apiVersion: v1
kind: Secret
metadata:
  name: voting-app-secrets
  labels:
    app: voting-app
type: Opaque
stringData:
  POSTGRES_HOST: voting-app-database
  POSTGRES_DB: votingdb
  POSTGRES_USER: voting
  POSTGRES_PASSWORD: voting
  PGADMIN_DEFAULT_EMAIL: admin@admin.com
  PGADMIN_DEFAULT_PASSWORD: admin
  BACKEND_PROTOCOL: http
  BACKEND_HOST: voting-app-backend
  BACKEND_PORT: "5001"
