apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-vote-frontend
  labels:
    app: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-app-vote-frontend
  template:
    metadata:
      labels:
        app: voting-app-vote-frontend
    spec:
      containers:
      - name: voting-app-vote-frontend
        image: ghcr.io/ni5o/voting-app-vote-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: BACKEND_PROTOCOL
          valueFrom:
            secretKeyRef:
              name: voting-app-secrets
              key: BACKEND_PROTOCOL
        - name: BACKEND_HOST
          valueFrom:
            secretKeyRef:
              name: voting-app-secrets
              key: BACKEND_HOST
        - name: BACKEND_PORT
          valueFrom:
            secretKeyRef:
              name: voting-app-secrets
              key: BACKEND_PORT
---
apiVersion: v1
kind: Service
metadata:
  name: voting-app-vote-frontend
  labels:
    app: voting-app
spec:
  selector:
    app: voting-app-vote-frontend
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: voting-app-vote-frontend
  labels:
    app: voting-app
spec:
  to:
    kind: Service
    name: voting-app-vote-frontend
  port:
    targetPort: 3000
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
